/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.adj.demo.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Candidate service. Represents a row in the &quot;POC_Candidate&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.adj.demo.model.impl.CandidateModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.adj.demo.model.impl.CandidateImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Candidate
 * @generated
 */
@ProviderType
public interface CandidateModel
	extends BaseModel<Candidate>, GroupedModel, ShardedModel,
			StagedAuditedModel, WorkflowedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a candidate model instance should use the {@link Candidate} interface instead.
	 */

	/**
	 * Returns the primary key of this candidate.
	 *
	 * @return the primary key of this candidate
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this candidate.
	 *
	 * @param primaryKey the primary key of this candidate
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this candidate.
	 *
	 * @return the uuid of this candidate
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this candidate.
	 *
	 * @param uuid the uuid of this candidate
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the candidate ID of this candidate.
	 *
	 * @return the candidate ID of this candidate
	 */
	public long getCandidateId();

	/**
	 * Sets the candidate ID of this candidate.
	 *
	 * @param candidateId the candidate ID of this candidate
	 */
	public void setCandidateId(long candidateId);

	/**
	 * Returns the group ID of this candidate.
	 *
	 * @return the group ID of this candidate
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this candidate.
	 *
	 * @param groupId the group ID of this candidate
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this candidate.
	 *
	 * @return the company ID of this candidate
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this candidate.
	 *
	 * @param companyId the company ID of this candidate
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this candidate.
	 *
	 * @return the user ID of this candidate
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this candidate.
	 *
	 * @param userId the user ID of this candidate
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this candidate.
	 *
	 * @return the user uuid of this candidate
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this candidate.
	 *
	 * @param userUuid the user uuid of this candidate
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this candidate.
	 *
	 * @return the user name of this candidate
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this candidate.
	 *
	 * @param userName the user name of this candidate
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this candidate.
	 *
	 * @return the create date of this candidate
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this candidate.
	 *
	 * @param createDate the create date of this candidate
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this candidate.
	 *
	 * @return the modified date of this candidate
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this candidate.
	 *
	 * @param modifiedDate the modified date of this candidate
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the first name of this candidate.
	 *
	 * @return the first name of this candidate
	 */
	@AutoEscape
	public String getFirstName();

	/**
	 * Sets the first name of this candidate.
	 *
	 * @param firstName the first name of this candidate
	 */
	public void setFirstName(String firstName);

	/**
	 * Returns the last name of this candidate.
	 *
	 * @return the last name of this candidate
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this candidate.
	 *
	 * @param lastName the last name of this candidate
	 */
	public void setLastName(String lastName);

	/**
	 * Returns the phone no of this candidate.
	 *
	 * @return the phone no of this candidate
	 */
	@AutoEscape
	public String getPhoneNo();

	/**
	 * Sets the phone no of this candidate.
	 *
	 * @param phoneNo the phone no of this candidate
	 */
	public void setPhoneNo(String phoneNo);

	/**
	 * Returns the email of this candidate.
	 *
	 * @return the email of this candidate
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this candidate.
	 *
	 * @param email the email of this candidate
	 */
	public void setEmail(String email);

	/**
	 * Returns the skills of this candidate.
	 *
	 * @return the skills of this candidate
	 */
	@AutoEscape
	public String getSkills();

	/**
	 * Sets the skills of this candidate.
	 *
	 * @param Skills the skills of this candidate
	 */
	public void setSkills(String Skills);

	/**
	 * Returns the education of this candidate.
	 *
	 * @return the education of this candidate
	 */
	@AutoEscape
	public String getEducation();

	/**
	 * Sets the education of this candidate.
	 *
	 * @param education the education of this candidate
	 */
	public void setEducation(String education);

	/**
	 * Returns the status of this candidate.
	 *
	 * @return the status of this candidate
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this candidate.
	 *
	 * @param status the status of this candidate
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this candidate.
	 *
	 * @return the status by user ID of this candidate
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this candidate.
	 *
	 * @param statusByUserId the status by user ID of this candidate
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this candidate.
	 *
	 * @return the status by user uuid of this candidate
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this candidate.
	 *
	 * @param statusByUserUuid the status by user uuid of this candidate
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this candidate.
	 *
	 * @return the status by user name of this candidate
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this candidate.
	 *
	 * @param statusByUserName the status by user name of this candidate
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this candidate.
	 *
	 * @return the status date of this candidate
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this candidate.
	 *
	 * @param statusDate the status date of this candidate
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns <code>true</code> if this candidate is approved.
	 *
	 * @return <code>true</code> if this candidate is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this candidate is denied.
	 *
	 * @return <code>true</code> if this candidate is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this candidate is a draft.
	 *
	 * @return <code>true</code> if this candidate is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this candidate is expired.
	 *
	 * @return <code>true</code> if this candidate is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this candidate is inactive.
	 *
	 * @return <code>true</code> if this candidate is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this candidate is incomplete.
	 *
	 * @return <code>true</code> if this candidate is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this candidate is pending.
	 *
	 * @return <code>true</code> if this candidate is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this candidate is scheduled.
	 *
	 * @return <code>true</code> if this candidate is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

	@Override
	public Candidate cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}